[package]
name = "raytracing_rs"
version = "0.1.0"
edition = "2024"

[release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
incremental = false
strip = true

[build]
rustflags = ["-C", "target-cpu=native", "-C", "target-feature=+avx2"]

[dependencies]
